theme: jekyll-theme-slate

# Site settings
title: Par2MultiChecker
description: > # this means to ignore newlines until "baseurl:"
  Par2MultiChecker Ultimate Edition is a tool designed to be a straight forward solution for verifying PAR2, SFV and MD5 files and also repair PAR2 files as well as extract files from ZIP and RAR archives and Join Split-ted files all in one Easy-to-use interface.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sites.google.com/site/tsdarkness/par2multichecker" # the base hostname & protocol for your site
collections:
